### PR TITLE
Added example in README.md

### LINKED ISSUE #3: Add more example for better understanding
I tried to add autoresponse when someone else's pull request is merged into my repo
but it works fine for me only ,i.e. sends a auto message when I merge my own pull request

shows the following check fails ->

image

### PR DESCRIPTION
**Pull request by AB-san**
closes #3
Added an another example - auto message when pr is merged successfully  under Usage section

### CODE REVIEW

**Comment by AB-san** [comment]
@derekprior  please review my pr :)

**Comment by AB-san** [comment]
@derekprior please review this pr , if you want any changes please let me know

**Comment by derekprior** [comment]
Merged, thanks!

**Comment by AB-san** [comment]
> Merged, thanks!

Welcome :)

**Pull request merged**
